---
- name: "Add modules on modules.conf"
  lineinfile:
    dest: /etc/modules-load.d/modules.conf
    regexp: "^{{ item }}"
    line: "{{ item }}"
    state: present
  with_items:
    - "{{ modules_add_list }}"

- name: "Remove modules on modules.conf"
  lineinfile:
    dest: /etc/modules-load.d/modules.conf
    regexp: "^{{ item }}"
    state: absent
  with_items:
    - "{{ modules_remove_list }}"

- name: "Immediately Load modules"
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ modules_add_list }}"

- name: "Immediately Remove modules"
  modprobe:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ modules_remove_list }}"
